### ISSUE TITLE
Bot Crash when encountering special char username

### ISSUE THREAD

**Issue by Vikaton** [aatxe/irc#29]
`thread '<main>' panicked at 'index 1 and/or 2 in `ɸ` do not lie on character boundary', ../src/libcore/str/mod.rs:1534` is the error I get when joining a channel with someone named `ɸ` maybe slicing strings with `.chars()` might help?

**Comment by aatxe** [comment]
Can you provide a backtrace for this?

**Comment by Vikaton** [comment]
```
stack backtrace:                                                                                                                                                         
   1:     0x7f67a83028be - sys::backtrace::write::h42ae15d4d8dc9021Lqs                                                                                                   
   2:     0x7f67a8305e75 - panicking::on_panic::h16e339088a7da9f0l8w                                                                                                     
   3:     0x7f67a82fbfee - rt::unwind::begin_unwind_inner::hb0ccf650c87729feZNw                                                                                          
   4:     0x7f67a82fc5ac - rt::unwind::begin_unwind_fmt::he51a7264215a12fc5Mw                                                                                            
   5:     0x7f67a8305866 - rust_begin_unwind                                                                                                                             
   6:     0x7f67a8332234 - panicking::panic_fmt::hf59daa1a4a5468ee19B                                                                                                    
   7:     0x7f67a833354f - str::slice_error_fail::h52ce5f58099fc839w9J                                                                                                   
   8:     0x7f67a8291901 - str::traits::str.ops..Index<ops..RangeFrom<usize>>::index::h6fd567aa6ccbbd50JZJ                                                               
                        at ../src/libcore/str/mod.rs:1454                                                                                                                
   9:     0x7f67a829686e - client::data::user::AccessLevelIterator<'a>.Iterator::next::h1299c46ebe42ac8dr3e                                                              
                        at /home/vikaton/.cargo/registry/src/github.com-0a35038f75765ae4/irc-0.8.14/src/client/data/user.rs:192                                          
  10:     0x7f67a8296986 - vec::Vec<T>::extend_desugared::h12816073599069841150                                                                                          
                        at ../src/libcollections/vec.rs:1569                                                                                                             
  11:     0x7f67a8296709 - vec::Vec<T>.FromIterator<T>::from_iter::h5996158128275431698                                                                                  
                        at ../src/libcollections/vec.rs:1493                                                                                                             
  12:     0x7f67a82964ae - iter::Iterator::collect::h9567461806700210410                                                                                                 
                        at ../src/libcore/iter.rs:563                                                                                                                    
  13:     0x7f67a82960d1 - client::data::user::User::new::h3702fa5ad044b10c6Pe                                                                                           
                        at /home/vikaton/.cargo/registry/src/github.com-0a35038f75765ae4/irc-0.8.14/src/client/data/user.rs:21                                           
  14:     0x7f67a8250470 - client::server::IrcServer<T, U>::handle_message::h5406990844272688805                                                                         
                        at /home/vikaton/.cargo/registry/src/github.com-0a35038f75765ae4/irc-0.8.14/src/client/server/mod.rs:131                                         
  15:     0x7f67a824d871 - client::server::ServerIterator<'a, T, U>.Iterator::next::closure.3427                                                                         
                        at /home/vikaton/.cargo/registry/src/github.com-0a35038f75765ae4/irc-0.8.14/src/client/server/mod.rs:291                                         
  16:     0x7f67a824d61c - result::Result<T, E>::and_then::h7042714658168574316                                                                                          
                        at ../src/libcore/result.rs:603                                                                                                                  
  17:     0x7f67a824d2e0 - client::server::ServerIterator<'a, T, U>.Iterator::next::h6889142576820972592                                                                 
                        at /home/vikaton/.cargo/registry/src/github.com-0a35038f75765ae4/irc-0.8.14/src/client/server/mod.rs:288                                         
  18:     0x7f67a823a859 - main::he6dc31d48d47c7bahaa                                                                                                                    
                        at src/main.rs:17                                                                                                                                
  19:     0x7f67a830ad08 - rust_try_inner                                                                                                                                
  20:     0x7f67a830acf5 - rust_try                                                                                                                                      
  21:     0x7f67a83079a8 - rt::lang_start::h5cc45221c651f24bi3w                                                                                                          
  22:     0x7f67a826ac6b - main                                                                                                                                          
  23:     0x7f67a741bb44 - __libc_start_main                                                                                                                             
  24:     0x7f67a8239dc8 - <unknown>                                                                                                                                     
  25:                0x0 - <unknown>                                                                                                                                     
An unknown error occurred                                                                                                                                                
                                                                                                                                                                         
To learn more, run the command again with --verbose.                                                                                                                     
```

**Comment by aatxe** [comment]
Thanks! Good catch!
